const $=s=>document.querySelector(s);let coaches=[],courses=[];const money=v=>`MYR ${Number(v||0).toFixed(2)}`;function auth(){return {authorization:`Bearer ${$('#token').value.trim()}`,'content-type':'application/json'}}function msg(t,e=false){$('#msg').textContent=t;$('#msg').className=`status${e?' error':''}`}
async function get(url){const r=await fetch(url,{headers:auth(),cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}async function post(url,b){const r=await fetch(url,{method:'POST',headers:auth(),body:JSON.stringify(b)}),d=await r.json().catch(()=>({}));if(!r.ok)throw Error(d.error||`HTTP ${r.status}`);return d}
async function load(){try{msg('Loading...');const [a,b,s]=await Promise.all([get('/api/admin/coaches'),get('/api/admin/coach-assignments'),get('/api/admin/coach-service-assignments')]);coaches=a.coaches||[];courses=a.courses||[];renderCoaches();renderSelectors();renderAssignments(b.assignments||[]);renderServices(s.assignments||[]);msg('Coach data loaded.')}catch(e){msg(e.message,true)}}
function renderCoaches(){$('#coachRows').innerHTML=coaches.length?coaches.map(c=>`<tr><td><b>${c.coach_code}</b></td><td>${c.full_name}</td><td>${c.email}</td><td><select data-status="${c.id}"><option ${c.status==='Pending'?'selected':''}>Pending</option><option ${c.status==='Approved'?'selected':''}>Approved</option><option ${c.status==='Suspended'?'selected':''}>Suspended</option><option ${c.status==='Archived'?'selected':''}>Archived</option></select></td><td><input type="checkbox" data-portal="${c.id}" ${Number(c.portal_enabled)?'checked':''}></td><td>${c.bank_name||'—'}<br>${c.bank_account_number||''}</td><td><button class="btn secondary" data-save="${c.id}">Save</button></td></tr>`).join(''):'<tr><td colspan="7">No coaches yet.</td></tr>';document.querySelectorAll('[data-save]').forEach(x=>x.onclick=()=>saveCoach(Number(x.dataset.save)))}

function courseLabel(sku,name){
  const S=String(sku||'').trim(),N=String(name||'').trim();
  if(!S)return N;
  if(!N)return S;
  const rx=new RegExp('^'+S.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')+'\\s*[-–—:·]?\\s*','i');
  const cleaned=N.replace(rx,'').trim();
  return cleaned?`${S} · ${cleaned}`:S;
}

function renderSelectors(){const approved=coaches.filter(c=>c.status==='Approved'),opts=approved.map(c=>`<option value="${c.id}">${c.coach_code} · ${c.full_name}</option>`).join('');$('#aCoach').innerHTML=opts;$('#sCoach').innerHTML=opts;$('#aCourse').innerHTML=courses.map(c=>`<option value="${c.id}" data-sku="${c.sku||''}" data-name="${c.name_en||c.name_zh||c.sku||''}" data-start="${c.starts_on||''}" data-end="${c.ends_on||''}">${courseLabel(c.sku,c.name_en||c.name_zh||'')}</option>`).join('');courseChanged()}
function renderAssignments(rows){$('#assignmentRows').innerHTML=rows.length?rows.map(a=>{const removable=!Number(a.participant_count_locked)&&a.final_commission==null&&!['Conducted','Cancelled'].includes(String(a.course_status||''));return `<tr><td><b>${courseLabel(a.course_sku,a.course_name)}</b></td><td>${a.coach_code}<br>${a.coach_name}</td><td>${a.course_status}${Number(a.participant_count_locked)?' · Closed':''}</td><td>${a.participant_count}${Number(a.participant_count_locked)?' 🔒':''}</td><td>${money(a.eligible_course_revenue)}</td><td>${Number(a.commission_rate||0).toFixed(2)}% + ${money(a.commission_fixed_amount)}</td><td><b>${money(a.potential_commission)}</b></td><td>${a.final_commission==null?'—':money(a.final_commission)}</td><td>${a.closing_date||'—'}</td><td>${removable?`<button class="btn secondary" data-remove-course="${a.id}">Remove</button>`:'<span class="muted">Locked</span>'}</td></tr>`}).join(''):'<tr><td colspan="10">No coach course assignments yet.</td></tr>';document.querySelectorAll('[data-remove-course]').forEach(x=>x.onclick=()=>removeCourse(Number(x.dataset.removeCourse)))}
function renderServices(rows){$('#serviceRows').innerHTML=rows.length?rows.map(a=>`<tr><td><b>${a.service_name}</b><br>${a.service_code}</td><td>${a.coach_code}<br>${a.coach_name}</td><td>${a.effective_from}${a.effective_until?' → '+a.effective_until:' → Ongoing'}</td><td>${a.case_count}</td><td>${money(a.eligible_service_revenue)}</td><td>${Number(a.commission_rate||0).toFixed(2)}%${Number(a.commission_fixed_amount)?' + '+money(a.commission_fixed_amount):''}</td><td><b>${money(a.potential_commission)}</b></td><td>${a.status}</td><td>${a.status==='Active'?`<button class="btn secondary" data-end-service="${a.id}">End Assignment</button>`:'<span class="muted">Ended</span>'}</td></tr>`).join(''):'<tr><td colspan="9">No coach service assignments yet.</td></tr>';document.querySelectorAll('[data-end-service]').forEach(x=>x.onclick=()=>endService(Number(x.dataset.endService)))}

async function removeCourse(id){
  if(!confirm('Remove this open coach-course assignment? This is allowed only before the assignment is closed/finalized.'))return;
  try{await post('/api/admin/coach-assignments',{action:'remove',id});msg('Course coach assignment removed.');await load()}catch(e){msg(e.message,true)}
}
async function endService(id){
  if(!confirm('End this ongoing service assignment? Historical activity will be preserved.'))return;
  try{await post('/api/admin/coach-service-assignments',{action:'end',id});msg('Service coach assignment ended.');await load()}catch(e){msg(e.message,true)}
}

async function saveCoach(id){try{const c=coaches.find(x=>x.id===id),status=document.querySelector(`[data-status="${id}"]`).value,portal=document.querySelector(`[data-portal="${id}"]`).checked;await post('/api/admin/coaches',{action:'update',id,full_name:c.full_name,display_name:c.display_name,email:c.email,phone:c.phone,country:c.country,bank_name:c.bank_name,bank_account_name:c.bank_account_name,bank_account_number:c.bank_account_number,status,portal_enabled:portal,notes:c.notes});await load()}catch(e){msg(e.message,true)}}
function addDays(s,n){if(!s)return '';const d=new Date(`${s}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+n);return d.toISOString().slice(0,10)}
function courseChanged(){const o=$('#aCourse').selectedOptions[0];if(!o)return;if(o.dataset.start)$('#aStart').value=o.dataset.start.slice(0,10);if(o.dataset.end){$('#aEnd').value=o.dataset.end.slice(0,10);$('#aClose').value=addDays($('#aEnd').value,5);$('#aClose').min=$('#aEnd').value;$('#aClose').max=addDays($('#aEnd').value,5)}}
$('#load').onclick=load;$('#createCoach').onclick=async()=>{try{await post('/api/admin/coaches',{action:'create',full_name:$('#cName').value,email:$('#cEmail').value,phone:$('#cPhone').value,country:$('#cCountry').value,bank_name:$('#cBank').value,bank_account_name:$('#cBankName').value,bank_account_number:$('#cBankNo').value,password:$('#cPassword').value,status:$('#cStatus').value,portal_enabled:$('#cPortal').value==='1'});msg('Coach created.');await load()}catch(e){msg(e.message,true)}};
$('#aCourse').onchange=courseChanged;$('#aEnd').onchange=()=>{$('#aClose').min=$('#aEnd').value;$('#aClose').max=addDays($('#aEnd').value,5);$('#aClose').value=addDays($('#aEnd').value,5)};
$('#assign').onclick=async()=>{try{const o=$('#aCourse').selectedOptions[0];await post('/api/admin/coach-assignments',{coach_id:Number($('#aCoach').value),product_id:Number($('#aCourse').value),course_sku:o?.dataset.sku||'',course_name:o?.dataset.name||'',course_start_date:$('#aStart').value,course_end_date:$('#aEnd').value,closing_date:$('#aClose').value,commission_rate:Number($('#aRate').value||0),commission_fixed_amount:Number($('#aFixed').value||0)});msg('Course coach assignment saved.');await load()}catch(e){msg(e.message,true)}};
$('#assignService').onclick=async()=>{try{await post('/api/admin/coach-service-assignments',{coach_id:Number($('#sCoach').value),service_code:$('#sService').value,effective_from:$('#sFrom').value,effective_until:$('#sUntil').value,commission_rate:Number($('#sRate').value||0),commission_fixed_amount:Number($('#sFixed').value||0),status:$('#sStatus').value});msg('Service coach assignment saved.');await load()}catch(e){msg(e.message,true)}};
