const $=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c])),money=v=>`MYR ${Number(v||0).toFixed(2)}`,token=()=>localStorage.getItem('qy_coach_token')||'';
function rule(x){return `${Number(x.commission_rate||0).toFixed(2)}%${Number(x.commission_fixed_amount||0)?` + ${money(x.commission_fixed_amount)}`:''}`}
function dedupeCourseName(sku,name){const s=String(sku||'').trim(),n=String(name||'').trim();if(!s)return n;if(!n)return s;const re=new RegExp(`^${s.replace(/[.*+?^${}()|[\]\\]/g,'\\$&')}\\s*[-:·]?\\s*`,'i');return n.replace(re,'').trim()||n}
function monthLabel(period){if(!/^\d{4}-\d{2}$/.test(period||''))return period||'';const [y,m]=period.split('-').map(Number);return new Date(y,m-1,1).toLocaleDateString('en-MY',{month:'long',year:'numeric'})}
async function load(){const r=await fetch('/api/coach/me',{headers:{authorization:`Bearer ${token()}`},cache:'no-store'}),d=await r.json().catch(()=>({}));if(!r.ok){localStorage.removeItem('qy_coach_token');location.href='/coach-login';return}
  $('#welcome').textContent=`Welcome, ${d.coach.display_name||d.coach.full_name}`;$('#code').textContent=`Coach Code: ${d.coach.coach_code}`;
  const a=d.assignments||[],s=d.services||[],p=d.payouts||[],cp=d.summary?.current_period||'';
  $('#mCourses').textContent=a.length;$('#mParticipants').textContent=a.reduce((z,x)=>z+Number(x.participant_count||0),0);
  const potentialCard=$('#mPotential');potentialCard.textContent=money(d.summary?.current_month_potential||0);const potentialLabel=potentialCard?.parentElement?.querySelector('span');if(potentialLabel)potentialLabel.textContent=`Potential Commission · ${monthLabel(cp)}`;
  $('#mApproved').textContent=money(d.summary?.approved_not_paid);$('#mPaid').textContent=money(d.summary?.paid_commission);
  $('#courses').innerHTML=a.length?a.map(x=>`<tr><td><b>${esc(x.course_sku||'')}</b>${x.course_name?`<br>${esc(dedupeCourseName(x.course_sku,x.course_name))}`:''}</td><td>${esc(x.course_start_date||'—')} → ${esc(x.course_end_date||'—')}<br><span class="muted">Close: ${esc(x.closing_date||'—')}</span></td><td>${esc(x.course_status)}</td><td>${Number(x.participant_count||0)}${Number(x.participant_count_locked)?' 🔒':''}</td><td>${money(x.eligible_course_revenue)}</td><td>${rule(x)}</td><td><b>${money(x.potential_commission)}</b></td><td>${x.final_commission==null?'—':`<b>${money(x.final_commission)}</b>`}</td><td>${esc(x.payout_eligible_month||'—')}</td></tr>`).join(''):'<tr><td colspan="9">No assigned courses yet.</td></tr>';
  $('#services').innerHTML=s.length?s.map(x=>`<tr><td><b>${esc(x.service_name)}</b></td><td>${esc(x.effective_from)} → ${esc(x.effective_until||'Ongoing')}</td><td>${esc(x.status)}</td><td>${Number(x.case_count||0)}</td><td>${money(x.eligible_service_revenue)}</td><td>${rule(x)}</td><td><b>${money(x.potential_commission)}</b></td></tr>`).join(''):'<tr><td colspan="7">No service assignments yet.</td></tr>';
  $('#payouts').innerHTML=p.length?p.map(x=>`<tr><td>${esc(x.payout_period)}</td><td>${esc(x.payout_reference)}</td><td>${money(x.course_revenue)}</td><td>${money(x.service_revenue)}</td><td><b>${money(x.total_commission)}</b></td><td>${esc(x.status)}</td><td>${esc(x.payment_date||'—')}</td><td>${esc(x.payment_reference||'—')}</td></tr>`).join(''):'<tr><td colspan="8">No payout history yet.</td></tr>'}
$('#logout').onclick=async()=>{try{await fetch('/api/coach/logout',{method:'POST',headers:{authorization:`Bearer ${token()}`}})}catch{}localStorage.removeItem('qy_coach_token');location.href='/coach-login'};load();
