import {clean,config,signature,requestTarget,logEvent} from './_shared.js';
function eq(a,b){a=String(a||'');b=String(b||'');if(a.length!==b.length)return false;let d=0;for(let i=0;i<a.length;i++)d|=a.charCodeAt(i)^b.charCodeAt(i);return d===0}
export async function onRequestPost(context){
 const raw=await context.request.text();let p={};try{p=JSON.parse(raw)}catch{return new Response('INVALID',{status:400})}
 let cfg;try{cfg=config(context.env)}catch{return new Response('NOT CONFIGURED',{status:503})}
 const h=context.request.headers,client=h.get('Client-Id')||h.get('client-id')||'',rid=h.get('Request-Id')||h.get('request-id')||'',ts=h.get('Request-Timestamp')||h.get('request-timestamp')||'',received=h.get('Signature')||h.get('signature')||'';
 const target=new URL(context.request.url).pathname;const expected=await signature(cfg.secret,client,rid,ts,target,raw);const verified=client===cfg.clientId&&eq(received,expected);
 const ref=clean(p?.order?.invoice_number||p?.invoice_number||p?.order?.invoiceNumber,100),tx=clean(p?.transaction?.id||p?.transaction?.transaction_id||p?.payment?.transaction_id||p?.uuid,120),status=clean(p?.transaction?.status||p?.payment?.status||p?.status,40).toUpperCase();
 await logEvent(context.env.ENQUIRIES_DB,{eventType:'Notification',orderRef:ref,transactionId:tx,status,message:'DOKU server notification',signature:received,verified,payload:p});if(!verified)return new Response('INVALID SIGNATURE',{status:401});
 // Safety rule: only an explicit SUCCESS status can mark paid. Unknown Malaysia notification shapes are logged but not promoted.
 if(ref&&['SUCCESS','PAID'].includes(status)){
  const db=context.env.ENQUIRIES_DB,o=await db.prepare(`SELECT id,total,currency,payment_status FROM orders WHERE order_reference=? LIMIT 1`).bind(ref).first();if(o){const now=new Date().toISOString();let py=await db.prepare(`SELECT id FROM payments WHERE order_id=? AND provider='DOKU' ORDER BY id DESC LIMIT 1`).bind(o.id).first();if(py)await db.prepare(`UPDATE payments SET provider_transaction_id=?,amount=?,currency=?,status='Paid',raw_reference=?,paid_at=?,payment_method='DOKU',gross_amount=?,verification_status='Verified',verified_at=?,customer_receipt_issuer='Quantum YiJing',gateway_message=?,gateway_hash_verified=1 WHERE id=?`).bind(tx,Number(o.total||0),o.currency||'MYR',`DOKU:${tx}`,now,Number(o.total||0),now,status,py.id).run();else await db.prepare(`INSERT INTO payments(order_id,provider,provider_transaction_id,amount,currency,status,raw_reference,paid_at,payment_method,gross_amount,provider_fee,net_amount,settlement_date,bank_received_amount,verification_status,verified_at,customer_receipt_issuer,notes,gateway_mode,gateway_message,gateway_hash_verified) VALUES(?,?,?,?,?,'Paid',?,?, 'DOKU',?,0,0,'',0,'Verified',?,'Quantum YiJing','Gateway payment verified; settlement awaiting reconciliation.','',?,1)`).bind(o.id,'DOKU',tx,Number(o.total||0),o.currency||'MYR',`DOKU:${tx}`,now,Number(o.total||0),now,status).run();await db.prepare(`UPDATE orders SET payment_provider='DOKU',payment_status='Paid',external_order_id=?,updated_at=CURRENT_TIMESTAMP WHERE id=?`).bind(tx,o.id).run();}}
 return new Response('OK',{status:200,headers:{'content-type':'text/plain; charset=utf-8'}})
}
export function onRequest(c){return c.request.method==='POST'?onRequestPost(c):new Response('Method Not Allowed',{status:405})}
